meta_product_name: "Dare2Bet"
meta_title: "Dare2Bet - Bet against your friends, and the world!"
meta_description: "Dare2Bet allows you to challenge your friends to bets and make them public! No more empty bets!"
meta_image: "pigpurple.png" # should exist in `app/assets/images/`
